name: gh-pages

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          DENO_INSTALL: /home/runner/.deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno --version
          deno upgrade --version 1.4.6
          deno install --unstable --allow-env --allow-read --allow-write --allow-net --allow-run -n pagic https://deno.land/x/pagic@v0.10.3/mod.ts
          pagic build

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GA_ID: UA-169223577-1
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: es-interview.js.org
